// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/site.ts";
import * as $$$0 from "./loaders/generateOpenapi.ts";
import * as $$$1 from "./loaders/sendToGithub.ts";
import * as $$$$$$0 from "./sections/Footer.tsx";
import * as $$$$$$1 from "./sections/GeneratePr.tsx";
import * as $$$$$$2 from "./sections/LandingPage/Background.tsx";
import * as $$$$$$3 from "./sections/LandingPage/BackgroundWrapper.tsx";
import * as $$$$$$4 from "./sections/LandingPage/CustomFooter.tsx";
import * as $$$$$$5 from "./sections/LandingPage/Hero.tsx";
import * as $$$$$$6 from "./sections/LandingPage/LandingPage.tsx";
import * as $$$$$$7 from "./sections/LandingPage/NavBar.tsx";
import * as $$$$$$8 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/generateOpenapi.ts": $$$0,
    "site/loaders/sendToGithub.ts": $$$1,
  },
  "sections": {
    "site/sections/Footer.tsx": $$$$$$0,
    "site/sections/GeneratePr.tsx": $$$$$$1,
    "site/sections/LandingPage/Background.tsx": $$$$$$2,
    "site/sections/LandingPage/BackgroundWrapper.tsx": $$$$$$3,
    "site/sections/LandingPage/CustomFooter.tsx": $$$$$$4,
    "site/sections/LandingPage/Hero.tsx": $$$$$$5,
    "site/sections/LandingPage/LandingPage.tsx": $$$$$$6,
    "site/sections/LandingPage/NavBar.tsx": $$$$$$7,
    "site/sections/Theme/Theme.tsx": $$$$$$8,
  },
  "apps": {
    "site/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
