// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/site.ts";
import * as $$$0 from "./loaders/generateOpenapi.ts";
import * as $$$1 from "./loaders/sendToGithub.ts";
import * as $$$$$$0 from "./sections/Footer.tsx";
import * as $$$$$$1 from "./sections/GeneratePr.tsx";
import * as $$$$$$2 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/generateOpenapi.ts": $$$0,
    "site/loaders/sendToGithub.ts": $$$1,
  },
  "sections": {
    "site/sections/Footer.tsx": $$$$$$0,
    "site/sections/GeneratePr.tsx": $$$$$$1,
    "site/sections/Theme/Theme.tsx": $$$$$$2,
  },
  "apps": {
    "site/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
